runtime: python
env: flex
entrypoint: gunicorn -t 0 -b :$PORT app:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 15

beta_settings:
  cloud_sql_instances: buzzerfinder-355616:asia-southeast2:buzzerfinder