"""Initial migration.

Revision ID: 270c1403b1ac
Revises: 
Create Date: 2022-06-30 14:18:41.507863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '270c1403b1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', mysql.INTEGER(display_width=10), autoincrement=True, nullable=False),
    sa.Column('id_tweet', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('tweet', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_user', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('followers_count', mysql.INTEGER(display_width=8), autoincrement=False, nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
